export const AUTH_ERRORS = {
  // Signup
  INVALID_NAME_FORMAT: "INVALID_NAME_FORMAT",
  ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS",
  INVALID_USERNAME_FORMAT: "INVALID_USERNAME_FORMAT",
  USERNAME_ALREADY_TAKEN: "USERNAME_ALREADY_TAKEN",
  WEAK_PASSWORD: "WEAK_PASSWORD",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",

  // OTP
  OTP_NOT_FOUND: "OTP_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_ALREADY_VERIFIED: "OTP_ALREADY_VERIFIED",
  OTP_MAX_ATTEMPTS_EXCEEDED: "OTP_MAX_ATTEMPTS_EXCEEDED",
  OTP_RESEND_COOLDOWN_ACTIVE: "OTP_RESEND_COOLDOWN_ACTIVE",

  // Signup Session
  INVALID_SIGNUP_SESSION: "INVALID_SIGNUP_SESSION",
  INVALID_SIGNUP_TOKEN: "INVALID_SIGNUP_TOKEN",
  SIGNUP_ALREADY_VERIFIED: "SIGNUP_ALREADY_VERIFIED",
  SIGNUP_VERIFICATION_REQUIRED: "SIGNUP_VERIFICATION_REQUIRED",
  PENDING_SIGNUP_NOT_FOUND: "PENDING_SIGNUP_NOT_FOUND",
  PENDING_SIGNUP_CORRUPTED: "PENDING_SIGNUP_CORRUPTED",

  // Guest Upgrade
  INVALID_GUEST_UPGRADE_ROLE: "INVALID_GUEST_UPGRADE_ROLE",

  // Login
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SOCIAL_LOGIN_REQUIRED: "SOCIAL_LOGIN_REQUIRED",
  PASSWORD_LOGIN_UNAVAILABLE: "PASSWORD_LOGIN_UNAVAILABLE",

  // Refresh Token
  REFRESH_TOKEN_MISSING: "REFRESH_TOKEN_MISSING",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_REFRESH_SESSION: "INVALID_REFRESH_SESSION",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

  // Password Reset
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  SOCIAL_LOGIN_PASSWORD_RESET_UNAVAILABLE:
    "SOCIAL_LOGIN_PASSWORD_RESET_UNAVAILABLE",

  // OAuth
  INVALID_GOOGLE_USER_DATA: "INVALID_GOOGLE_USER_DATA",
  GOOGLE_EMAIL_NOT_VERIFIED: "GOOGLE_EMAIL_NOT_VERIFIED",
  GOOGLE_ACCOUNT_ALREADY_LINKED: "GOOGLE_ACCOUNT_ALREADY_LINKED",
  INVALID_OAUTH_SIGNUP_TOKEN: "INVALID_OAUTH_SIGNUP_TOKEN",
  INVALID_OAUTH_SIGNUP_PAYLOAD: "INVALID_OAUTH_SIGNUP_PAYLOAD",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EXISTING_USER_NOT_FOUND: "EXISTING_USER_NOT_FOUND",
  ACCOUNT_EMAIL_CORRUPTED: "ACCOUNT_EMAIL_CORRUPTED",

  // Role
  INVALID_PUBLIC_ROLE: "INVALID_PUBLIC_ROLE",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERRORS)[keyof typeof AUTH_ERRORS];